#!/bin/sh

export TERMINAL="~/.local/bin/xdg-terminal-exec"
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.config/x11/xresources
~/.fehbg &
dunst &
pipewire &
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &

bspc config normal_border_color "#2E3440"
bspc config active_border_color "#4C566A"
bspc config focused_border_color "#4C566A"
bspc config presel_feedback_color "#4C566A"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2px
bspc config window_gap          5px

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
